proje/cloud/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static
app_name = 'cloud'

urlpatterns = [
    path('', views.cloud_home, name='cloud_home'),
    path('save_project/', views.save_project, name='save_project'),
    
    path('delete_server/', views.delete_server, name='delete_server'),
    
    path('create-server', views.create_server, name='create-server'),
    path('clone_vm', views.clone_vm, name='clone_vm'),
    path('wait' , views.wait , name='wait'),
    path('my_form_view', views.my_form_view, name='my_form_view'),
    path('deneme' , views.deneme , name='deneme'),
    path('project-view/<int:project_id>', views.view_server, name='project-view'),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

proje/vdsal/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('django.contrib.auth.urls')),
    path('account/', include('account.urls')),
    path('cloud/', include('cloud.urls', namespace='cloud')),
    

    
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

proje/templates/deneme.html
<!DOCTYPE html>
<html>
<head>
    <title>VM Config</title>
</head>
<body>
    <h2>Configure VM</h2>
    <form action="{% url 'cloud:deneme' %}" method="post">
        <!-- Django requires this line for CSRF protection -->
        {% csrf_token %}

        <label for="name">Hostname:</label><br>
        <input type="text" id="name" name="name" value=""><br>


        <label for="ram">RAM:</label><br>
        <select id="ram" name="ram">
            <option value="1024">1 GB</option>
            <option value="2048">2 GB</option>
            <option value="4096">4 GB</option>
            <option value="8192">8 GB</option>
            <!-- Add more options as needed -->
        </select><br>

        <label for="disk">Disk:</label><br>
        <input type="text" id="disk" name="disk" value="50G"><br>



        <input type="submit" value="Submit">
    </form>
</body>
</html>

proje/templates/login.html
{% load static %}

<!doctype html>
<html lang="en">
  
<!-- Mirrored from templates.iqonic.design/qlouddash/html/backend/auth-sign-in.html by HTTrack Website Copier/3.x [XR&CO'2014], Fri, 05 May 2023 22:54:16 GMT -->
<head>
   <meta charset="utf-8">
     <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
     <title>QloudDash | Responsive Bootstrap 4 Admin Dashboard Template</title>
     
     <!-- Favicon -->
     <link rel="shortcut icon" href="https://templates.iqonic.design/qlouddash/html/assets/images/favicon.ico" />
     <link rel="stylesheet" href="{% static 'css/backend-plugin.min.css' %}">
     <link rel="stylesheet" href="{% static 'css/backende209.css?v=1.0.0' %}">
     <link rel="stylesheet" href="{% static 'vendor/@fortawesome/fontawesome-free/css/all.min.css' %}">
     <link rel="stylesheet" href="{% static 'vendor/line-awesome/dist/line-awesome/css/line-awesome.min.css' %}">
     <link rel="stylesheet" href="{% static 'vendor/remixicon/fonts/remixicon.css' %}">
     <link rel="stylesheet" href="{% static 'vendor/@icon/dripicons/dripicons.css' %}">
     
     <link rel='stylesheet' href="{% static 'vendor/fullcalendar/core/main.css' %}" />
     <link rel='stylesheet' href="{% static 'vendor/fullcalendar/daygrid/main.css' %}" />
     <link rel='stylesheet' href="{% static 'vendor/fullcalendar/timegrid/main.css' %}" />
     <link rel='stylesheet' href="{% static 'vendor/fullcalendar/list/main.css' %}" />
     <link rel="stylesheet" href="{% static 'vendor/mapbox/mapbox-gl.css' %}">  </head>
  <body class=" ">
    <!-- loader Start -->
    <div id="loading">
          <div id="loading-center">
          </div>
    </div>
    <!-- loader END -->
    
      <div class="wrapper">
      <section class="login-content">
         <div class="container">
            <div class="row align-items-center justify-content-center height-self-center">
               <div class="col-lg-8">
                  <div class="card auth-card">
                     <div class="card-body p-0">
                        <div class="d-flex align-items-center auth-content">
                           <div class="col-lg-6 align-self-center">
                              <div class="p-3">
                                 
                                 <h2 class="mb-2">Log In</h2>
                                 
                                 <p>Login to stay connected.</p>
                                 {% if messages %}
    {% for message in messages %}
        <div class="alert alert-{{ message.tags }}">
            {{ message }}
        </div>
    {% endfor %}
{% endif %}
                                 <form action="" method="POST">
                                    {% csrf_token %}
                                    <div class="row">
                                       <div class="col-lg-12">
                                          <div class="floating-label form-group">
                                             <input class="floating-input form-control" name ="email" type="email" placeholder=" ">
                                             <label>Email</label>
                                          </div>
                                       </div>
                                       <div class="col-lg-12">
                                          <div class="floating-label form-group">
                                             <input class="floating-input form-control" name ="password" type="password" placeholder=" ">
                                             <label>Password</label>
                                          </div>
                                       </div>
                                       <div class="col-lg-6">
                                          <div class="custom-control custom-checkbox mb-3">
                                             <input type="checkbox" class="custom-control-input" id="customCheck1">
                                             <label class="custom-control-label control-label-1" for="customCheck1">Remember Me</label>
                                          </div>
                                       </div>
                                       <div class="col-lg-6">
                                          <a href="" class="text-primary float-right mb-lg-0 mb-3">Forgot Password?</a>
                                       </div>
                                    </div>
                                    <button type="submit" class="btn btn-primary">Sign In</button>
                                    <p class="mt-3">
                                       Create an Account <a href="register_user" class="text-primary">Register</a>
                                    </p>
                                 </form>
                              </div>
                           </div>
                           <div class="col-lg-6 content-right">
                              <img src="{% static 'images/login/sign-in.png' %}" class="img-fluid image-right" alt="">
                           </div>
                        </div>
                     </div>
                  </div>
               </div>
            </div>
         </div>
      </section>
      </div>
    
    <!-- Backend Bundle JavaScript -->
    <script src="{% static 'js/backend-bundle.min.js' %}"></script>
    
    <!-- Flextree Javascript-->
    <script src="{% static 'js/flex-tree.min.js' %}"></script>
    <script src="{% static 'js/tree.js' %}"></script>
    
    <!-- Table Treeview JavaScript -->
    <script src="{% static 'js/table-treeview.js' %}"></script>
    
    <!-- Masonary Gallery Javascript -->
    <script src="{% static 'js/masonry.pkgd.min.js' %}"></script>
    <script src="{% static 'js/imagesloaded.pkgd.min.js' %}"></script>
    
    <!-- Mapbox Javascript -->
    <script src="{% static 'js/mapbox-gl.js' %}"></script>
    <script src="{% static 'js/mapbox.js' %}"></script>
    
    <!-- Fullcalender Javascript -->
    <script src="{% static 'vendor/fullcalendar/core/main.js' %}"></script>
    <script src="{% static 'vendor/fullcalendar/daygrid/main.js' %}"></script>
    <script src="{% static 'vendor/fullcalendar/timegrid/main.js' %}"></script>
    <script src="{% static 'vendor/fullcalendar/list/main.js' %}"></script>
    
    <!-- SweetAlert JavaScript -->
    <script src="{% static 'js/sweetalert.js' %}"></script>
    
    <!-- Vectoe Map JavaScript -->
    <script src="{% static 'js/vector-map-custom.js' %}"></script>
    
    <!-- Chart Custom JavaScript -->
    <script src="{% static 'js/customizer.js' %}"></script>
    
    <!-- Chart Custom JavaScript -->
    <script src="{% static 'js/chart-custom.js' %}"></script>
    
    <!-- slider JavaScript -->
    <script src="{% static 'js/slider.js' %}"></script>
    
    <!-- app JavaScript -->
    <script src="{% static 'js/app.js' %}"></script>
  </body>

<!-- Mirrored from templates.iqonic.design/qlouddash/html/backend/auth-sign-in.html by HTTrack Website Copier/3.x [XR&CO'2014], Fri, 05 May 2023 22:54:17 GMT -->
</html>

proje/templates/register.html
{% load static %}


<!doctype html>
<html lang="en">
  
<!-- Mirrored from templates.iqonic.design/qlouddash/html/backend/auth-sign-up.html by HTTrack Website Copier/3.x [XR&CO'2014], Fri, 05 May 2023 22:54:17 GMT -->
<head>
    <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
      <title>QloudDash | Responsive Bootstrap 4 Admin Dashboard Template</title>
      
<!-- Favicon -->
<link rel="shortcut icon" href="https://templates.iqonic.design/qlouddash/html/assets/images/favicon.ico" />
<link rel="stylesheet" href="{% static 'css/backend-plugin.min.css' %}">
<link rel="stylesheet" href="{% static 'css/backende209.css?v=1.0.0' %}">
<link rel="stylesheet" href="{% static 'vendor/@fortawesome/fontawesome-free/css/all.min.css' %}">
<link rel="stylesheet" href="{% static 'vendor/line-awesome/dist/line-awesome/css/line-awesome.min.css' %}">
<link rel="stylesheet" href="{% static 'vendor/remixicon/fonts/remixicon.css' %}">
<link rel="stylesheet" href="{% static 'vendor/@icon/dripicons/dripicons.css' %}">

<link rel='stylesheet' href="{% static 'vendor/fullcalendar/core/main.css' %}" />
<link rel='stylesheet' href="{% static 'vendor/fullcalendar/daygrid/main.css' %}" />
<link rel='stylesheet' href="{% static 'vendor/fullcalendar/timegrid/main.css' %}" />
<link rel='stylesheet' href="{% static 'vendor/fullcalendar/list/main.css' %}" />
<link rel="stylesheet" href="{% static 'vendor/mapbox/mapbox-gl.css' %}">  </head>
<body class=" ">
<!-- loader Start -->
    <div id="loading">
          <div id="loading-center">
          </div>
    </div>
    <!-- loader END -->
    
      <div class="wrapper">
      <section class="login-content">
         <div class="container">
            <div class="row align-items-center justify-content-center height-self-center">
               <div class="col-lg-8">
                  <div class="card auth-card">
                     <div class="card-body p-0">
                        <div class="d-flex align-items-center auth-content">
                           <div class="col-lg-6 align-self-center">
                              <div class="p-3">
                                 <h2 class="mb-2">Register</h2>
                                 <p>Create your vdsal account.</p>
                                 <form action="" method="POST">
                                    {% csrf_token %}
                                    <div class="row">
                                       <div class="col-lg-6">
                                          <div class="floating-label form-group">
                                             <input class="floating-input form-control" name ="first_name" type="text" placeholder=" ">
                                             <label>First Name</label>
                                          </div>
                                       </div>
                                       <div class="col-lg-6">
                                          <div class="floating-label form-group">
                                             <input class="floating-input form-control" name ="last_name" type="text" placeholder=" ">
                                             <label>Last Name</label>
                                          </div>
                                       </div>
                                       <div class="col-lg-6">
                                          <div class="floating-label form-group">
                                             <input class="floating-input form-control" name ="email" type="email" placeholder=" ">
                                             <label>Email</label>
                                          </div>
                                       </div>
                                       <div class="col-lg-6">
                                          <div class="floating-label form-group">
                                             <input class="floating-input form-control" name ="phone" type="text" placeholder=" ">
                                             <label>Phone No.</label>
                                          </div>
                                       </div>
                                       <div class="col-lg-6">
                                          <div class="floating-label form-group">
                                             <input class="floating-input form-control" name ="password" type="password" placeholder=" ">
                                             <label>Password</label>
                                          </div>
                                       </div>
                                       <div class="col-lg-6">
                                          <div class="floating-label form-group">
                                             <input class="floating-input form-control" name ="password2" type="password" placeholder=" ">
                                             <label>Confirm Password</label>
                                          </div>
                                       </div>
                                       <div class="col-lg-12">
                                          <div class="custom-control custom-checkbox mb-3">
                                             <input type="checkbox" class="custom-control-input" id="customCheck1">
                                             <label class="custom-control-label" for="customCheck1">I agree with the terms of use</label>
                                          </div>
                                       </div>
                                    </div>
                                    <button type="submit" class="btn btn-primary">Sign Up</button>
                                    <p class="mt-3">
                                       Already have an Account <a href="login_user" class="text-primary">Log In</a>
                                    </p>
                                 </form>
                              </div>
                           </div>
                           <div class="col-lg-6 content-right">
                              <img src="{% static 'images/login/sign-up.png' %}" class="img-fluid image-right" alt="">
                           </div>
                        </div>
                     </div>
                  </div>
               </div>
            </div>
         </div>
      </section>
      </div>
    
    <!-- Backend Bundle JavaScript -->
    <script src="{% static 'js/backend-bundle.min.js' %}"></script>
    
    <!-- Flextree Javascript-->
    <script src="{% static 'js/flex-tree.min.js' %}"></script>
    <script src="{% static 'js/tree.js' %}"></script>
    
    <!-- Table Treeview JavaScript -->
    <script src="{% static 'js/table-treeview.js' %}"></script>
    
    <!-- Masonary Gallery Javascript -->
    <script src="{% static 'js/masonry.pkgd.min.js' %}"></script>
    <script src="{% static 'js/imagesloaded.pkgd.min.js' %}"></script>
    
    <!-- Mapbox Javascript -->
    <script src="{% static 'js/mapbox-gl.js' %}"></script>
    <script src="{% static 'js/mapbox.js' %}"></script>
    
    <!-- Fullcalender Javascript -->
    <script src="{% static 'vendor/fullcalendar/core/main.js' %}"></script>
    <script src="{% static 'vendor/fullcalendar/daygrid/main.js' %}"></script>
    <script src="{% static 'vendor/fullcalendar/timegrid/main.js' %}"></script>
    <script src="{% static 'vendor/fullcalendar/list/main.js' %}"></script>
    
    <!-- SweetAlert JavaScript -->
    <script src="{% static 'js/sweetalert.js' %}"></script>
    
    <!-- Vectoe Map JavaScript -->
    <script src="{% static 'js/vector-map-custom.js' %}"></script>
    
    <!-- Chart Custom JavaScript -->
    <script src="{% static 'js/customizer.js' %}"></script>
    
    <!-- Chart Custom JavaScript -->
    <script src="{% static 'js/chart-custom.js' %}"></script>
    
    <!-- slider JavaScript -->
    <script src="{% static 'js/slider.js' %}"></script>
    
    <!-- app JavaScript -->
    <script src="{% static 'js/app.js' %}"></script>
  </body>

<!-- Mirrored from templates.iqonic.design/qlouddash/html/backend/auth-sign-up.html by HTTrack Website Copier/3.x [XR&CO'2014], Fri, 05 May 2023 22:54:17 GMT -->
</html>

proje/templates/server_view.html
<!DOCTYPE html>
<html>
<head>
    <title>Sunucu Bilgileri</title>
</head>
<body>
    <h1>Sunucu Bilgileri</h1>
    <p>Sunucu ID: {{ vm_config.vmid }}</p>
    <p>Sunucu İsmi: {{ vm_config.name }}</p>
    <p>Sunucu Durumu: {{ vm_config.status }}</p>
    <p>Sunucu CPU: {{ vm_config.cpus }}</p>
    <p>Sunucu RAM: {{ vm_config.maxmem|filesizeformat }}</p>
    <p>Toplam Disk Alanı: {{ vm_config.disk|filesizeformat }}</p>

    
</body>
</html>