proje/cloud/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static
app_name = 'cloud'

urlpatterns = [
    path('', views.cloud_home, name='cloud_home'),
    path('save_project/', views.save_project, name='save_project'),
    
    path('delete_server/', views.delete_server, name='delete_server'),
    
    path('create-server', views.create_server, name='create-server'),
    path('clone_vm', views.clone_vm, name='clone_vm'),
    path('wait' , views.wait , name='wait'),
    path('my_form_view', views.my_form_view, name='my_form_view'),
    path('deneme' , views.deneme , name='deneme'),
    path('project-view/<int:project_id>', views.view_server, name='project-view'),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

proje/vdsal/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('django.contrib.auth.urls')),
    path('account/', include('account.urls')),
    path('cloud/', include('cloud.urls', namespace='cloud')),
    

    
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

proje/cloud/models.py
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()

class Project(models.Model):
    project_name = models.CharField(max_length=255)
    project_description = models.TextField()
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.project_name







class server_ips(models.Model):
    name = models.CharField(max_length=255)
    ip = models.CharField(max_length=255)
    subnet = models.CharField(max_length=255)
    location = models.CharField(max_length=255)
    def __repr__(self):
        return str(self.ip)



class server_packages(models.Model):
    package_name = models.CharField(max_length=255)
    package_cpu = models.CharField(max_length=255)
    package_ram = models.CharField(max_length=255)
    package_disk = models.CharField(max_length=255)
    package_price = models.CharField(max_length=255)
    package_transfer_limit = models.CharField(max_length=255)
    def __str__(self):
        return self.package_name
    
    class Meta:
        verbose_name_plural = "server_packages"

class server_os(models.Model):
    os_name = models.CharField(max_length=255)
    os_version = models.CharField(max_length=255)
    clone_name = models.CharField(max_length=255)
    clone_id = models.CharField(max_length=255)
    img_url = models.ImageField(upload_to='static/images/os' , null=True)
    def __str__(self):
        return self.os_name    
    class Meta:
        verbose_name_plural = "server_os"


class server_locations(models.Model):
    location_name = models.CharField(max_length=255)
    location_city = models.CharField(max_length=255)
    img_url = models.ImageField(upload_to='static/images/locations' , null=True)
    def __str__(self):
        return self.location_name   
    class Meta:
        verbose_name_plural = "server_locations"



class servers(models.Model):
    vm_id = models.CharField(max_length=255 , null=True)
    server_name = models.CharField(max_length=255)
    server_pack = models.ForeignKey(server_packages, on_delete=models.CASCADE, null=True)
    server_ip = models.ForeignKey(server_ips, on_delete=models.CASCADE)
    server_os = models.ForeignKey(server_os, on_delete=models.CASCADE)
    server_location = models.ForeignKey(server_locations, on_delete=models.CASCADE)
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    def __str__(self):
        return self.server_name
    class Meta:
        verbose_name_plural = "servers"

proje/cloud/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse,HttpResponse
from .models import Project 
from .models import server_packages
from .models import servers
from .models import server_os
from .models import server_locations
import requests
import json
from proxmoxer import ProxmoxAPI
import time
import paramiko
from django.views.decorators.csrf import csrf_exempt
import urllib3

urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)
proxmox = ProxmoxAPI('46.196.48.16', user='root@pam', password='123qweQWE', verify_ssl=False)
node = proxmox.nodes('vcenter')
proxmox.login()
@login_required(login_url="/account/login_user")
def cloud_home(request):
    projects = Project.objects.filter(user=request.user)
    return render(request, 'cloud/index.html', {'projects': projects})


@login_required(login_url="/account/login_user")
def save_project(request):
    if request.method == 'POST':
        project_name = request.POST.get('project_name')
        project_description = request.POST.get('project_description')
        user_id = request.user.id

        # Proje modeline kaydet
        project = Project(project_name=project_name, project_description=project_description, user_id=user_id)
        project.save()

        return JsonResponse({'success': True})
    else:
        return JsonResponse({'success': False})





def create_server2(request):
    return render(request,'cloud/create-server.html')


def delete_server(request):
    node.qemu('101').delete()
    return HttpResponse("VM Silindi.")

def view_server_kopya(request):
    vm_config = node.qemu('101').status.current.get()
    return render(request, 'server_view.html', {'vm_config': vm_config})





def create_server(request):
    
    os = server_os.objects.all()
    location = server_locations.objects.all()
    server_package = server_packages.objects.all()
    project_id = request.session.get('project_id' , None)
    if request.method == 'POST':
        pack_id = request.POST.get('packId')
        location_id = request.POST.get('locationId')
        os_id = request.POST.get('osId')
        pack = server_packages.objects.get(id=pack_id)
        name = request.POST.get('hostname')
        ram = int(pack.package_ram)* 1024
        cpu = int(pack.package_cpu)
        disk = int(pack.package_disk)
        try:
            vmid = 101
            target_node = 'vcenter'  # Klonun yerleştirileceği hedef düğümü belirtin
            new_vmid = 1002  # Klonun yeni VM ID'sini belirtin
            server_add = servers(server_name = name , server_ip_id=1 , server_os_id = os_id, server_location_id = location_id , server_pack_id = pack_id , vm_id=new_vmid , project_id = project_id )
            server_add.save()
            
            # Klonlama işlemini gerçekleştir
            

            proxmox.nodes(target_node).qemu(vmid).clone.create(newid=new_vmid, name=name )
            # Klonlama işleminin tamamlanmasını bekle
            time.sleep(80)

            # Klonun RAM diskini güncelle
            
            
                    # SSH bağlantısı için gerekli bilgiler
            host = '46.196.48.16'
            port = 22
            username = 'root'
            password = '123qweQWE'

                # SSH bağlantısını oluşturma
            ssh = paramiko.SSHClient()
            ssh.set_missing_host_key_policy(paramiko.AutoAddPolicy())
            ssh.connect(host, port, username, password)
                # RAM ayarlama
                
            ram_cmd = f"qm set {new_vmid} --memory {ram}"
            stdin, stdout, stderr = ssh.exec_command(ram_cmd)
            ram_output = stdout.read().decode()

                # Disk boyutunu değiştirme
            new_disk_size = f'{disk}G'
            resize_cmd = f"qm resize {new_vmid} scsi0 {new_disk_size}"
            stdin, stdout, stderr = ssh.exec_command(resize_cmd)
            resize_output = stdout.read().decode()

                # CPU ayarlama
                
            cpu_cmd = f"qm set {new_vmid} --cores {cpu}"
            stdin, stdout, stderr = ssh.exec_command(cpu_cmd)
            cpu_output = stdout.read().decode()

                # SSH bağlantısını kapatma
            ssh.close()

        # İşlem sonuçlarını gösterme
            response_ram = f"RAM Ayarı: {ram_output}<br> Disk Boyutu Ayarı: {resize_output}<br> CPU Ayarı: {cpu_output}"
                
            return HttpResponse(response_ram)
            
        except Exception as e:
            print("Hata:", str(e))
            return HttpResponse("Bir hata oluştu. Lütfen tekrar deneyin.")  # veya başka bir hata mesajı

    else:
        return render(request, 'cloud/create/index.html', {'server_package': server_package , 'os':os , 'location' : location , 'project_id': project_id } )




def wait(request):
    vm_config = node.qemu('1002').status.current.get()
    return render(request , 'cloud/wait.html' , {'vm_config':vm_config})



def clone_vm(request):
    try:
        # ubuntu-server'ın VM ID'sini bulun
        source_vm_id = None
        for node in proxmox.nodes.get():
            if node['node'] == 'vcenter':
                for vm in proxmox.nodes(node['node']).qemu.get():
                    if vm.get('name') == 'ubuntu-server':
                        source_vm_id = vm.get('vmid')
                        break
        # Eğer bulunduysa, klonla ve yeni VM oluştur
        if source_vm_id is not None:
            # yeni bir vmid alın, eşsiz olmalıdır
            new_vmid = str(max([int(vm['vmid']) for node in proxmox.nodes.get() for vm in proxmox.nodes(node['node']).qemu.get()]) + 1)
            node_name = 'vcenter'
            proxmox.nodes(node_name).qemu(source_vm_id).clone.post(newid=new_vmid, full='1', storage='local-lvm', target=node_name)
            # Klonlama işlemi tamamlanana kadar bekleyin
            time.sleep(80)
            # yeni VM oluşturulduktan sonra, konfigürasyonunu al ve değiştir
            config = proxmox.nodes(node_name).qemu(new_vmid).config.get()
            # RAM ve disk boyutunu ayarla
            config['memory'] = 2048  # RAM 2GB
            ssh = paramiko.SSHClient()
            ssh.set_missing_host_key_policy(paramiko.AutoAddPolicy())
            # SSH bağlantısı oluştur
            ssh.connect(hostname='46.196.48.16', username='root', password='123qweQWE')
            # Diski genişletme komutunu çalıştır
            stdin, stdout, stderr = ssh.exec_command('qm resize 102 scsi0 50G')
            # Çıktıyı yazdır
            print(stdout.read().decode())
            ssh.close()
            # 'meta', 'digest' ve 'vmgenid' öğelerini kaldırın çünkü Proxmox API'si bunları ayarlamayı kabul etmeyebilir
            config.pop('meta', None)
            config.pop('digest', None)
            config.pop('vmgenid', None)
            # yeni konfigürasyonu uygula
            proxmox.nodes(node_name).qemu(new_vmid).config.set(**config)
            return JsonResponse({'status': 'success'})
        else:
            return JsonResponse({'status': 'failiure'})
    except Exception as e:
        return JsonResponse({'status': 'failure', 'error': str(e)})

    






@csrf_exempt
def my_form_view(request):
    if request.method == 'POST':
        data = dict(request.POST.items())  # convert QueryDict to dictionary
        return JsonResponse(data)
    else:
        return JsonResponse({'error': 'Invalid request method'}, status=405)



def view_server(request  , project_id):
    vm_config = node.qemu('1002').status.current.get()
    server_list = servers.objects.filter(project_id=project_id)
    request.session['project_id'] = project_id
    if request.method == "POST":
       
        return None
    
    else:
        return render(request, "cloud/view/index.html" , {'server_list': server_list , 'vm_config' :vm_config })

def deneme(request):
    project_id = request.session.get('project_id' , None)
    print(project_id)
    return render(request, "cloud/view/index.html")





        
        
        

proje/templates/cloud/index.html
{%extends 'base/index.html'%}

{%block content %}

<div class="content-page">
    <div class="container-fluid">    
       <div class="row">
           <div class="col-lg-12">
               <ul class="nav nav-pills tab-pills" id="pills-tab" role="tablist">
                   <li class="nav-item">
                       <a class="nav-link active" data-toggle="pill" href="#all" role="tab" style="background-color: rgb(234, 234, 248);" aria-controls="all" aria-selected="true">Projects</a>
                   </li>
                   
               </ul>
                           
               <div class="card border-none">
                   <div class="card-body custom-card-space" style="background-color: rgb(234, 234, 248);">
                       <div class="tab-content task-content">
                           <div class="tab-pane fade show active" id="all" role="tabpanel"> 
                               <div class="row"> 
                                   
                                {% if projects %}
                                {% for i in projects%}
                                <div class=" col-lg-4 col-xl-3 col-md-6 ">               
                                    <div class="card">
                                        <div class="card-body dynamic-div">
                                            
                                                
                                                <input type="hidden" value="{{ i.id }}">
                                            
                                                <div class="dropdown">
                                                    <span class="dropdown-toggle" id="dropdownMenuButton03" data-toggle="dropdown">
                                                       <i class="ri-more-2-fill"></i>
                                                    </span>
                                                    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuButton03">
                                                       <a class="dropdown-item" href="#"><i class="ri-eye-line mr-3"></i>View</a>
                                                       <a class="dropdown-item" href="#"><i class="ri-delete-bin-6-line mr-3"></i>Delete</a> 
                                                    </div>
                                               </div>
                                            <h3 class="mb-2">{{i.project_name}}</h3>
                                            <p class="mb-0">{{i.project_description}}</p>
                                            
                                        </div>
                                    </div>
                                </div> 
                                
                           {%endfor%}
                      
                           {% endif %}
                   
                                
                                
                                
                                
                                <div class=" col-lg-4 col-xl-3 col-md-6 ">               
                                    <div class="card">
                                        <div class="card-body">
                                            <div class="d-flex align-items-top justify-content-between mb-4">
                                                
                                               
                                            </div>
                                            <button class="btn btn-primary btn-new render w-100" id="save-project-btn">Proje Ekle</button>
                                            
                                            
                                        </div>
                                    </div>
                                </div>
                                   
                               </div> 
                           </div>
                          
                       </div>
                   </div>
               </div>
           </div>
       </div>
       <!-- Page end  -->
   </div>
     </div>



     <div class="modal fade" id="project-modal"  tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
           <div class="modal-content">
              <div class="modal-header">
                 <h5 class="modal-title" id="exampleModalLabel">New project</h5>
                 <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                 <span aria-hidden="true">&times;</span>
                 </button>
              </div>
              <div class="modal-body">
                <form id="project-form" method="POST" action="{% url 'cloud:save_project' %}">
                    {% csrf_token %}
                    <label for="project_name">Project Name:</label>
                    <input type="text" class="form-control" name="project_name" required>
                    <br>
                    <label for="project_description">Project Description:</label>
                    <textarea name="project_description" class="form-control" required></textarea>
                    <br>
                
              </div>
              <div class="modal-footer">
                 <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                 <button type="submit" class="btn btn-primary">Save changes</button>
              </div>
            </form>
           </div>
        </div>
     </div>
     

  

{%endblock content %}

{%block css%}
<style>
.dynamic-div {
    position: relative;
    cursor: pointer;
    transition: border-color 0.3s ease;
  }

  .dynamic-div:hover {
    border: 5px solid #062b78;
  }
  .dropdown {
    position: absolute;
    top: 10px;
    right: 10px;
  }
</style>
  {%endblock css%}

{%block js %}

<script>
    // Modalı açan butonun tıklanma olayı
    document.getElementById('save-project-btn').addEventListener('click', function() {
        var modal = document.getElementById("project-modal");
        $(modal).modal('show');
    });

    

    // Proje formunun gönderilme olayı
    document.getElementById('project-form').addEventListener('submit', function(e) {
        e.preventDefault(); // Formun normal gönderimini engelle
        var formData = new FormData(this);

        // Proje formunu AJAX ile sunucuya gönder
        fetch(this.action, {
            method: 'POST',
            body: formData
        })
        .then(response => response.json())
        .then(data => {
            if (data.success) {
                alert('Proje başarıyla kaydedildi.');
                document.getElementById('project-modal').style.display = 'none';
                location.reload();
            } else {
                alert('Proje kaydedilirken bir hata oluştu.');
            }
        })
        .catch(error => {
            console.error('Proje kaydetme hatası:', error);
            alert('Proje kaydetme hatası.');
        });
    });
    var dropdowns = document.getElementsByClassName("dropdown");
  for (var i = 0; i < dropdowns.length; i++) {
    dropdowns[i].addEventListener("click", function(event) {
      event.stopPropagation();
    });
  }


    var dynamicDivs = document.getElementsByClassName("dynamic-div");
  for (var i = 0; i < dynamicDivs.length; i++) {
    dynamicDivs[i].addEventListener("click", function() {
      var inputField = this.querySelector("input");
      var value = inputField.value;
      var link = "project-view/";
      window.location.href = link + value;
    });
  }
</script>
{%endblock js %}

proje/templates/cloud/wait.html
<!DOCTYPE html>
<html>
<head>
  <title>VM Durumunu Kontrol Et</title>
  
</head>
<body>
  <h1>VM Durumunu Kontrol Et</h1>
  <div>
    <p><strong>Durum:</strong> <span id="status">{{ vm_config.status }}</span></p>
  </div>
</body>
</html>